X.
1	  error: rs10127775 is not a biallelic variant.,
2	  traceback: Traceback (most recent call last):\n  File \/analysistools/public_html/apps/LDlink/app/LDlink.py\, line 885, in ldproxy\n    with open('./tmp/proxy' + reference + '.txt', \r\) as fp:\nFileNotFoundError: [Errno 2] No such file or directory: './tmp/proxy1126195809.txt'\n
3	}
